### ISSUE TITLE
auto-complete freeze

### ISSUE THREAD

**Issue by githubSeb** [Azkae/emacs-config#5]
my completion get frozeen because of 3 lines in auto-complete.el. here is my patch, can you check it out ;-).

diff --git a/src/auto-complete/auto-complete/auto-complete.el b/src/auto-complete/auto-complete/auto-complete.el
index 71c85c5..6cfbc9b 100644
--- a/src/auto-complete/auto-complete/auto-complete.el
+++ b/src/auto-complete/auto-complete/auto-complete.el
@@ -816,13 +816,13 @@ You can not use it in source definition like (prefix . `NAME')."
         (popup-create point width height
                       :around t
                       :face 'ac-candidate-face
-                      :max-width ac-max-width
-                      :mouse-face 'ac-candidate-mouse-face
+                      ;; :width 'ac-max-width ;; DEBUG max-width ac-max-width
+                      ;; :mouse-face 'ac-candidate-mouse-face
                       :selection-face 'ac-selection-face
                       :symbol t
                       :scroll-bar t
                       :margin-left 1
-                      :keymap ac-menu-map
+                      ;; :keymap ac-menu-map
                       )))
 
 (defun ac-menu-delete ()
diff --git a/src/default-modules.el b/src/default-modules.el
index 4daaf97..5d39c4b 100644
--- a/src/default-modules.el
+++ b/src/default-modules.el
@@ -4,7 +4,6 @@
 ;; custom-modules will then be used instead of this file.
 
 (conf:load-module "emacs-settings")
-
 (conf:load-module "auto-complete")
 (conf:load-module "auto-complete-clang-async")
 (conf:load-module "autopair")

**Comment by Azkae** [comment]
Moved from auto-complete to company-mode.
